version: "3.8"

services:
  mn-example:
    build:
      context: .
    image: mn-example
    container_name: mn-example
    networks:
      - default
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
        reservations:
          memory: 512M

networks:
  default:
    external:
      name: env-local
