version: "3.8"

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    networks:
      - env-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_local:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    user: root

  micronaut-example:
    depends_on:
      - dynamodb-local
    build:
      context: .
    image: micronaut-example
    container_name: micronaut-example
    networks:
      - env-local
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 512M

networks:
  env-local:
    external: true

volumes:
  dynamodb_local:
    external: true
