micronaut:
  application:
    name: micronaut-example

  server:
    port: 8080
  #    netty:
  #      worker:
  #        event-loop-group: server

  http:
    client:
      event-loop-group: client

  netty:
    event-loops:
      client:
        num-threads: 2
#      server:
#        num-threads: 2

services:
  account:
    url: http://mock-server:3000

aws:
  #  localstack or dynamodb local only
  region: us-east-1
  accessKeyId: test
  secretKey: test
  endpointOverride: http://dynamodb-local:8000
